server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/turtle_trash_fighter?useSSL=false&serverTimezone=UTC
    username: root
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  application:
    name: comunidadettf

app:
  security:
    jwt:
      secret: troque-essa-chave-super-segura-para-o-spring-ttf-123456
      ttl-minutes: 120