### Health
GET http://localhost:8080/health


### Register

POST http://localhost:8080/auth/register
Content-Type: application/json

{
    "login":"srwedsar.com",
    "password":"123456",
    "nome":"werwedsre"
}


### Login

POST http://localhost:8080/auth/login
Content-Type: application/json

{
    "login":"sample@gmail.com",
    "password":"123456"
}


### Listar saves

GET http://localhost:8080/saves
Authorization: eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJzYW1wbGVAZ21haWwuY29tIiwibm9tZSI6IlVzdWFyaW8gVGVzdGUiLCJpYXQiOjE3ODE3NDA1MTcsImV4cCI6MTc4MTc0NzcxN30.8UkwLc4ckPx6jF0zZwmouDcw_RvpYOgjzxt255l14qAvAviPOBnIHJ6Tlynjyw88


### Buscar slot 0

GET http://localhost:8080/saves/0
Authorization: Bearer COLOQUE_TOKEN


### Salvar

PUT http://localhost:8080/saves
Content-Type: application/json
Authorization: Bearer COLOQUE_TOKEN

{
    "slotIndex":0,
    "slotName":"Save 1",
    "selectedCharacter":"Knight",
    "playTutorial":true,
    "difficulty":"NORMAL",
    "sceneName":"IntroScene",
    "checkpointId":"cp_001",
    "checkpoint":1,
    "collectedIdsJson":"[\"item_1\",\"item_2\"]",
    "deadEnemyIdsJson":"[\"enemy_1\"]",
    "completionPercent":12.5,
    "qttAppleCollected":0,
    "qttGlassCollected":0,
    "qttPlasticCollected":0,
    "qttEletronicsCollected":0,
    "qttPaperCollected":0,
    "qttMetalCollected":0,
    "Score":0
}


### Deletar

DELETE http://localhost:8080/saves/0
Authorization: Bearer COLOQUE_TOKEN